version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: metube_server_1
      APP_PORT: 9060

  server:
    image: alexta69/metube:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Aden
    volumes:
      - ${UMBREL_ROOT}/data/storage/downloads:/downloads
    ports:
       - 9060:8081
    restart: on-failure
